// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// PokemonLoader is an autogenerated mock type for the PokemonLoader type
type PokemonLoader struct {
	mock.Mock
}

// LoadPokemons provides a mock function with given fields:
func (_m *PokemonLoader) LoadPokemons() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPokemonLoader creates a new instance of PokemonLoader. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPokemonLoader(t testing.TB) *PokemonLoader {
	mock := &PokemonLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
