// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// CsvDataSource is an autogenerated mock type for the CsvDataSource type
type CsvDataSource struct {
	mock.Mock
}

// CSVPath provides a mock function with given fields:
func (_m *CsvDataSource) CSVPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ReadCollection provides a mock function with given fields:
func (_m *CsvDataSource) ReadCollection() ([][]string, error) {
	ret := _m.Called()

	var r0 [][]string
	if rf, ok := ret.Get(0).(func() [][]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCsvDataSource creates a new instance of CsvDataSource. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewCsvDataSource(t testing.TB) *CsvDataSource {
	mock := &CsvDataSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
