// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// AppController is an autogenerated mock type for the AppController type
type AppController struct {
	mock.Mock
}

// GetPokemon provides a mock function with given fields: c
func (_m *AppController) GetPokemon(c *gin.Context) {
	_m.Called(c)
}

// GetPokemons provides a mock function with given fields: c
func (_m *AppController) GetPokemons(c *gin.Context) {
	_m.Called(c)
}

// NewAppController creates a new instance of AppController. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewAppController(t testing.TB) *AppController {
	mock := &AppController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
