// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// PokemonController is an autogenerated mock type for the PokemonController type
type PokemonController struct {
	mock.Mock
}

// GetPokemon provides a mock function with given fields: c
func (_m *PokemonController) GetPokemon(c *gin.Context) {
	_m.Called(c)
}

// GetPokemons provides a mock function with given fields: c
func (_m *PokemonController) GetPokemons(c *gin.Context) {
	_m.Called(c)
}

// NewPokemonController creates a new instance of PokemonController. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPokemonController(t testing.TB) *PokemonController {
	mock := &PokemonController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
